export const DEFAULT_LIMITS = {
  maxLicenses: 100,
  maxProducts: 3,
  logRetention: 30,
  maxCustomers: 100,
  maxTeamMembers: 3,
  maxBlacklist: 100,
  maxStorage: 0,
  maxApiKeys: 10,
  maxReleasesPerProduct: 100,
  maxInvitations: 100,
  allowClassloader: false,
  allowCustomEmails: false,
  allowWatermarking: false,
};
